---
info:
  scm-url: "@scm.url@"
  build-url: "http://travis-ci.org/@env.TRAVIS_REPO_SLUG@/builds/@env.TRAVIS_BUILD_ID@"
  stage: test

logging:
  file: "target/boot-admin-sample.log"

management:
  endpoints:
    web:
      base-path: "/actuator"
  jolokia:
    enabled: true


spring:
  application:
    name: "@pom.artifactId@"
  boot:
    admin:
      client:
        url: http://localhost:8080
  profiles:
    active:
      - insecure

endpoints:
  health:
    enabled: true
  metrics:
    enabled: true
  logfile:
    enabled: true
  loggers:
    enabled: true
  trace:
    enabled: true
  auditevents:
    enabled: true
  heapdump:
    enabled: true
  threaddump:
    enabled: true
  env:
    enabled: true

---
spring:
  profiles: insecure

---
spring:
  profiles: secure
  boot:
    admin:
      client:
        username: "user"       #These two are needed so that the client
        password: "pass"       #can register at the protected server api
        instance:
          metadata:
            user.name: "user"         #These two are needed so that the server
            user.password: "pass"     #can access the proteceted client endpoints


