---
info:
  scm-url: "@scm.url@"
  build-url: "http://travis-ci.org/@env.TRAVIS_REPO_SLUG@/builds/@env.TRAVIS_BUILD_ID@"

logging:
  file: "target/boot-admin-sample.log"

management:
  endpoints:
    web:
      expose: "*"
  jolokia:
    enabled: true

spring:
  application:
    name: spring-boot-admin-sample
  boot:
    admin:
      client:
        url: http://localhost:8080
  profiles:
    active:
      - insecure

---
spring:
  profiles: insecure

---
spring:
  profiles: secure
  boot:
    admin:
      client:
        username: "user"       #These two are needed so that the client
        password: "pass"       #can register at the protected server api
        instance:
          metadata:
            user.name: "user"         #These two are needed so that the server
            user.password: "pass"     #can access the proteceted client endpoints


