spring:
  application:
    name: eureka-example
  cloud:
    config:
      enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

spring.boot.admin.routes.endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,activiti,logfile,refresh,flyway,liquibase,heapdump,hystrix.stream
