info:
  version: 1.0.0

spring:
  application:
    name: discovery-example
  cloud:
    config:
      enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/